### ISSUE TITLE
How is partial_pipeline_data loaded while validating email from a different browser? (Django Example) 

### ISSUE THREAD

**Issue by a1Gupta** [python-social-auth/social-examples#2]
I tried django-example with twitter backend with following pipelines -

```
SOCIAL_AUTH_PIPELINE = (
   # other pipelines
    'social_core.pipeline.user.get_username',
    'common.pipeline.require_email',
    'social_core.pipeline.mail.mail_validation',
    'social_core.pipeline.user.create_user',
   # more pipelines
)
```
I am still getting `AuthMissingParameter at /complete/twitter/ Missing needed parameter state` error in other browsers. The email verification link only has verification_code as query param. Can you tell how it will load data from Partial model from database ? There's no token or partial_token in query param in example.

**Comment by omab** [comment]
The new partial pipeline stores the data in the database and generates a token (uuid), this token can be used as the key to retrieve the data and continue with the process, the lib expects the token in a GET parameter under the name `partial_token`. In order to continue the process, the users must be redirect back with that parameter. The value for this parameter is accessible under the `current_partial` object in the pipeline function.

Also, check the docs, it might be more clear there https://python-social-auth.readthedocs.io/en/latest/pipeline.html#partial-pipeline

**Comment by a1Gupta** [comment]
The link to verify email is generated by this function -

```
def send_validation(strategy, backend, code):
    url = '{0}?verification_code={1}'.format(
        reverse('social:complete', args=(backend.name,)),
        code.code
    )
    url = strategy.request.build_absolute_uri(url)
    send_mail('Validate your account', 'Validate your account {0}'.format(url),
              settings.EMAIL_FROM, [code.email], fail_silently=False)
```

There is no parameter named `partial_token` here, how will it resume pipeline process in other browser. It's working fine when I am using same browser to validate the email.

**Comment by omab** [comment]
You are right, it's building a validation link with a token, but there's no reference to the `partial_token` parameter there, I'll work on a fix for it. Thanks!

**Comment by a1Gupta** [comment]
Apart from passing  `partial_token` in the parameter in email link what else I need to do. Which pipeline should I change to load partial pipeline data ?

**Comment by omab** [comment]
No extra change should be made, the lib will pickup the parameter value and load the data automatically and resume the pipeline.

**Comment by a1Gupta** [comment]
I checked by making this change, it wasn't working. I'll do it once again and confirm.

**Comment by omab** [comment]
@a1Gupta, this fix to social-core https://github.com/python-social-auth/social-core/commit/40d700650c14711bda5637e2279612e630ef52cc, and this change to examples https://github.com/python-social-auth/social-examples/commit/8fa7c8f1b51f26ef8c7bd871f0c035e8dd6505af makes it work as expected.

**Comment by a1Gupta** [comment]
@omab Thanks! Working as expected now :+1:
