### ISSUE TITLE
Django example error - No module named 'common'

### ISSUE THREAD

**Issue by mraak** [python-social-auth/social-examples#3]
I cloned the project, cd'd into _example-django_, installed the requirements one by one (pip install -r requirements.txt is failing for weird reasons). Then I ran `python manage.py migrate` and go this error.

```
File "E:\dev\projects\_testarea\social-examples\example-django\app\decorators.py", line 6, in <module>
    from common.utils import common_context
ModuleNotFoundError: No module named 'common'
```

**Comment by omab** [comment]
`common` is a symlink, I'm not sure if that works on Windows, you can copy the directory https://github.com/python-social-auth/social-examples/tree/master/example-common as `common` in `example-django` as a workaround.

**Comment by fe01134** [comment]
I hit this today on Mac.  Thank you your suggestion worked for me too.
